### ISSUE TITLE
New plugin icon

### ISSUE THREAD

**Issue by SPlanzer** [linz/QGIS-LDS-Plugin#19]
Plugin is no longer scoped to be LINZ specific but is still NZ specific 

LDS needs to be removed from the icon.
@pkinglinz do you have an pixels laying about such as the below but without "LDS" on it?

![icon](https://user-images.githubusercontent.com/10425696/45062632-e6c9cf00-b0fd-11e8-94e5-6ed28db8968a.png)

**Comment by SPlanzer** [comment]
LDS text to be removed prior to release

**Comment by pkinglinz** [comment]
will email you the svg in case i haven't already, the text is a layer so easy to remove

**Comment by SPlanzer** [comment]
Thanks @pkinglinz

**Comment by SPlanzer** [comment]
Done
