### ISSUE TITLE
Relabel the “import dataset” to “Add layer”

### ISSUE THREAD

**Issue by palmerj** [linz/QGIS-LDS-Plugin#6]
I think relabelling the “import dataset” to “Add layer” is a better option as the dataset is not really being imported only referenced by remote webservices (well not entirely true for WFS which does a full dataset cache for the session, but that's a small detail!)

**Comment by dwsilk** [comment]
Closed by https://github.com/linz/QGIS-LDS-Plugin/pull/10 ?

**Comment by SPlanzer** [comment]
Cheers @dwsilk 

I will be doing a push and clean up today on this repo

**Comment by SPlanzer** [comment]
done
